# Generated by Django 4.0.4 on 2022-06-22 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.CharField(max_length=50)),
                ('image_file', models.ImageField(upload_to='images/category')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Cloud Services'), (2, 'Webhosting Services'), (3, 'Collocation')], default=(1, 'Cloud Services'), unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.CharField(max_length=50)),
                ('payment_period', models.IntegerField(choices=[(0, 'Month'), (1, 'Year')], default=(0, 'Month'))),
                ('cost', models.FloatField(verbose_name='Cost (USD)')),
                ('cpu_type', models.CharField(choices=[('CPU', 'CPU'), ('VCPU', 'VCPU')], default='VCPU', max_length=6)),
                ('cpu', models.CharField(max_length=10)),
                ('memory_unit', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB')], default='GB', max_length=4)),
                ('memory', models.FloatField()),
                ('disk_type', models.CharField(choices=[('SYSTEM DISK', 'SYSTEM DISK'), ('SAS', 'SAS')], default='SYSTEM DISK', max_length=15)),
                ('disk', models.CharField(max_length=15, verbose_name='DISK (GB)')),
                ('bandwidth', models.CharField(choices=[('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('300GB Bandwidth', '300GB Bandwidth'), ('400GB Bandwidth', '400GB Bandwidth'), ('500GB Bandwidth', '500GB Bandwidth'), ('600GB Bandwidth', '600GB Bandwidth'), ('700GB Bandwidth', '700GB Bandwidth'), ('30TB Bandwidth', '30TB Bandwidth')], default=('Unlimited Bandwidth', 'Unlimited Bandwidth'), max_length=50)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalServiceType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('service_type', models.CharField(max_length=50)),
                ('payment_period', models.IntegerField(choices=[(0, 'Month'), (1, 'Year')], default=(0, 'Month'))),
                ('cost', models.FloatField(verbose_name='Cost (USD)')),
                ('cpu_type', models.CharField(choices=[('CPU', 'CPU'), ('VCPU', 'VCPU')], default='VCPU', max_length=6)),
                ('cpu', models.CharField(max_length=10)),
                ('memory_unit', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB')], default='GB', max_length=4)),
                ('memory', models.FloatField()),
                ('disk_type', models.CharField(choices=[('SYSTEM DISK', 'SYSTEM DISK'), ('SAS', 'SAS')], default='SYSTEM DISK', max_length=15)),
                ('disk', models.CharField(max_length=15, verbose_name='DISK (GB)')),
                ('bandwidth', models.CharField(choices=[('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('300GB Bandwidth', '300GB Bandwidth'), ('400GB Bandwidth', '400GB Bandwidth'), ('500GB Bandwidth', '500GB Bandwidth'), ('600GB Bandwidth', '600GB Bandwidth'), ('700GB Bandwidth', '700GB Bandwidth'), ('30TB Bandwidth', '30TB Bandwidth')], default=('Unlimited Bandwidth', 'Unlimited Bandwidth'), max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.category')),
            ],
            options={
                'verbose_name': 'historical service type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('service_category', models.CharField(max_length=50)),
                ('image_file', models.TextField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='services.service')),
            ],
            options={
                'verbose_name': 'historical category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='category',
            name='service_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
