# Generated by Django 4.0.5 on 2022-06-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_service_name', models.CharField(max_length=150, verbose_name='service name')),
                ('decription', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudServiceFlavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('cost', models.FloatField(verbose_name='Cost USD/Month')),
                ('decription', models.TextField(blank=True, max_length=200, null=True)),
                ('cloud_service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.cloudservice')),
            ],
        ),
        migrations.CreateModel(
            name='Webhosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhosting_service_name', models.CharField(max_length=150, verbose_name='service name')),
                ('decription', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhostingFlavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('cost_period', models.CharField(choices=[('Year', 'Year'), ('Month', 'Month')], default='USD/Month', max_length=6)),
                ('cost', models.FloatField(verbose_name='Cost (USD)')),
                ('decription', models.TextField(blank=True, max_length=200, null=True)),
                ('webhosting_service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.webhosting')),
            ],
        ),
        migrations.CreateModel(
            name='WebhostingOtherFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('webhosting_service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.webhostingflavour')),
            ],
        ),
        migrations.CreateModel(
            name='WebhostingHardwareREsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_type', models.CharField(choices=[('CPU', 'CPU'), ('VCPU', 'VCPU')], default='VCPU', max_length=6)),
                ('cpu', models.IntegerField()),
                ('memory_unit', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB')], default='GB', max_length=4)),
                ('memory', models.FloatField()),
                ('disk', models.FloatField(verbose_name='SYSTEM DISK (GB)')),
                ('bandwidth', models.CharField(choices=[('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('Unlimited Bandwidth', 'Unlimited Bandwidth'), ('300GB Bandwidth', '300GB Bandwidth'), ('400GB Bandwidth', '400GB Bandwidth'), ('500GB Bandwidth', '500GB Bandwidth'), ('600GB Bandwidth', '600GB Bandwidth'), ('700GB Bandwidth', '700GB Bandwidth'), ('30TB Bandwidth', '30TB Bandwidth')], default=('Unlimited Bandwidth', 'Unlimited Bandwidth'), max_length=50)),
                ('webhosting_service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.webhostingflavour')),
            ],
        ),
        migrations.CreateModel(
            name='CloudServiceOtherFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('cloud_service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.cloudserviceflavour')),
            ],
        ),
        migrations.CreateModel(
            name='CloudServiceHardwareResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_type', models.CharField(choices=[('CPU', 'CPU'), ('VCPU', 'VCPU')], default='VCPU', max_length=6)),
                ('cpu', models.IntegerField()),
                ('memory', models.FloatField(verbose_name='Memory (GB)')),
                ('disk_type', models.CharField(choices=[('SYSTEM DISK', 'SYSTEM DISK'), ('SAS', 'SAS')], default='SYSTEM DISK', max_length=15)),
                ('disk', models.FloatField(verbose_name='DISK (GB)')),
                ('cloud_service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.cloudserviceflavour')),
            ],
        ),
    ]
