# Generated by Django 4.0.4 on 2022-06-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='historicalservicetype',
            name='payment_period',
            field=models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], default=('Month', 'Month'), max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Cloud Services', 'Cloud Services'), ('Webhosting Services', 'Webhosting Services'), ('Collocation', 'Collocation')], default=('Cloud Services', 'Cloud Services'), max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='payment_period',
            field=models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], default=('Month', 'Month'), max_length=10),
        ),
    ]
