# Generated by Django 4.0.5 on 2022-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_cloudservice_image_cloudserviceflavour_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='service name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('decription', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
