# Generated by Django 4.0.5 on 2022-06-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudservice',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cloudserviceflavour',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='webhosting',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='webhostingflavour',
            old_name='decription',
            new_name='description',
        ),
    ]
