# Generated by Django 4.0.5 on 2022-06-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_decription_cloudservice_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TopLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.levelone')),
            ],
        ),
        migrations.CreateModel(
            name='LevelThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.leveltwo')),
            ],
        ),
        migrations.AddField(
            model_name='levelone',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.toplevel'),
        ),
    ]
