# Generated by Django 4.0.5 on 2022-06-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
    ]
