# Generated by Django 4.0 on 2022-06-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservicetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='description',
        ),
    ]
