# Generated by Django 4.0 on 2022-06-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_historicalservicetype_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherfeature',
            name='service_name',
        ),
        migrations.DeleteModel(
            name='HistoricalOtherFeature',
        ),
        migrations.DeleteModel(
            name='OtherFeature',
        ),
    ]
