# Generated by Django 4.0 on 2022-06-15 12:17

import core.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_otherfeature_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicetype',
            name='disk',
            field=models.CharField(max_length=15, validators=[core.services.models.Validate_disk_space], verbose_name='DISK (GB)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='disk',
            field=models.CharField(max_length=15, validators=[core.services.models.Validate_disk_space], verbose_name='DISK (GB)'),
        ),
    ]
