# Generated by Django 4.0 on 2022-06-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_historicalservicetype_disk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicetype',
            name='disk',
            field=models.CharField(max_length=15, verbose_name='DISK (GB)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='disk',
            field=models.CharField(max_length=15, verbose_name='DISK (GB)'),
        ),
    ]
