# Generated by Django 4.0 on 2022-06-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_historicalservicetype_disk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicetype',
            name='cpu',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='cpu',
            field=models.CharField(max_length=10),
        ),
    ]
