# Generated by Django 4.0.5 on 2022-06-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Your Email Address')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Your Phone Number')),
                ('message', models.TextField(max_length=1000, verbose_name='Your message')),
            ],
        ),
    ]
