# Generated by Django 3.2.13 on 2022-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(error_messages={'email': 'Email taken. Use a different one.'}, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(error_messages={'name': 'Name too long.'}, max_length=40, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(error_messages={'phone': 'Phone number too long.'}, max_length=10, unique=True, verbose_name='phone number'),
        ),
    ]
