# Generated by Django 3.2.13 on 2022-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220606_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(error_messages={'max_lenght': 'The message exceeds allowed character limit.'}, max_length=1000, verbose_name='description'),
        ),
    ]
